language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
    - .jest
before_script:
  - npm install -g npm@latest
  - npm install
  - npm install -g expo-cli
script:
  - npm ci
  - npm run test
  - echo $TRAVIS_PULL_REQUEST
# safelist
branches:
  only:
  - master
jobs:
  include:
    - stage: deploy
      node_js: lts/*
      if: $TRAVIS_PULL_REQUEST = "false"
      script:
        - npm ci
        - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - npx expo publish --non-interactive